"""initial migration

Revision ID: 93448b22692d
Revises: 
Create Date: 2024-11-04 11:59:01.642055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93448b22692d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('responsibilities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('rotba', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('responsibility_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('details', sa.Text(), nullable=False),
    sa.Column('responsibility_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('CONFERENCE', 'LETTER', name='responsibilitytype'), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['responsibility_id'], ['responsibilities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('responsibility_users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('responsibility_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['responsibility_id'], ['responsibility_items.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('responsibility_users')
    op.drop_table('responsibility_items')
    op.drop_table('users')
    op.drop_table('responsibilities')
    # ### end Alembic commands ###
